workspace = { members = ["unitracker-chsu"] }
[package]
name = "unitracker-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unitracker_chsu = { path = "./unitracker-chsu" }
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
reqwest = "0.12.5"
chrono = "0.4.34"
dotenv = "0.15.0"
clokwerk = "0.4.0"
# ratatui = "0.29.0"
comfy-table = "7.2.1"
