workspace = { members = ["unitracker-chsu", "unitracker-postgres"] }
[package]
name = "unitracker-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unitracker_chsu = { path = "./unitracker-chsu" }
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
reqwest = "0.11.24"
chrono = "0.4.34"
