[package]
name = "unitracker-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
chrono.workspace = true
serde.workspace = true
axum = { version = "0.8.4", features = ["json"] }
unitracker-psql.workspace = true
